### ISSUE TITLE
Light switch to on if I ask Siri to shut down a light that is already off

### ISSUE THREAD

**Issue by Bl4ckfi3lds** [fanta759/homebridge-jeedom-platform#22]
Hello, 

I have an issue with the plugin.

It's working almost perfectly except for one issue. if I ask Siri to shutdown a light that is already Off, it will activate the light.
I have the same problem the other way around, if I ask Siri to activate a light that is already On, the light will switch Off.

I only have the problem with Siri, every manual command in the home app works fine and the status is always good.

Thanks in advance

**Comment by fanta759** [comment]
Hello,
how your light ar configure in jeedom ?
There are in toggle mode ?

Fanta

**Comment by fanta759** [comment]
Hello,
how your light ar configure in jeedom ?
There are in toggle mode ?

Fanta

**Comment by Bl4ckfi3lds** [comment]
Hello,

You will find the screen capture attach below. I don't think they are in toggle mod in Jeedom but I am not really sure what you are calling 'toggle mod'
On my Jeedom page I have a dedicated ON button, an OFF button and a TOGGLE button.

If I try to press "ON" on my Jeedom page when the light is on, nothing append, same for the OFF button when the light is off.

<img width="234" alt="Capture d’écran 2022-10-19 à 20 57 54" src="https://user-images.githubusercontent.com/48182839/196780189-4482fafc-b19f-4d59-b689-e09c0c134a98.png">
<img width="1494" alt="Capture d’écran 2022-10-19 à 20 49 10" src="https://user-images.githubusercontent.com/48182839/196779132-c9263069-23d5-496d-8888-227f8865defc.png">
<img width="1467" alt="Capture d’écran 2022-10-19 à 20 49 52" src="https://user-images.githubusercontent.com/48182839/196779137-5e4d6c7c-f3cb-4c4b-9e9e-96daf3885442.png">
<img width="1526" alt="Capture d’écran 2022-10-19 à 20 49 30" src="https://user-images.githubusercontent.com/48182839/196779143-91196281-9989-46dd-8ea7-12bda9c469e6.png">

Regards,

Bl4ckfi3lds

**Comment by Bl4ckfi3lds** [comment]
Hello,

Update on the case, I know where the problem is but I still don't know the cause.

The parameters of the JeedomPlatformAccessory objects "onCmdId!" and "offCmdId" are wrong, they are assigned to the ID of the toggle command (9 in the example in my last post)

On my case I know that for all my device, if X is the ID of the toggle command, the ID of the ON command will be X-2 and the ID of the OFF command is X-1.

I have modify code for the functions in /src/platformAccessory.ts "setCharacteristicOn(cmd);" and "(this.setCharacteristicOff(cmd);" to reflect this.

So now it is working for me but it's a temporary fix. Have you an idea how your code could set the wrong ID to the commands ? For me my lights are configured properly in Jeedom.

Regards

Bl4ckfi3lds

**Comment by fanta759** [comment]
Bonjour Bl4ckfi3lds,
à la vue de tes screens, j'en déduis que tu es français.
Si ce n'ai pas le cas je retraduirai mon message.

Merci pour ton retour, je vais regarder dans le code pourquoi le toggle est pris en 1er au lieu des commandes On et Off.
Je te fais un retour dès que je peux.

Fanta759

**Comment by fanta759** [comment]
Je viens de publier une mise à jour qui permet de dissocier les commandes ON/OFF du TOGGLE.
Peux-tu me valider que ça corrige ton problème ?
Merci
Fanta759

**Comment by Bl4ckfi3lds** [comment]
Bonjour,

Je suis bien français ^^

J'ai installé la mise à jour puis j'ai bien testé toutes les commandes par Siri.
Tout marche parfaitement maintenant.

Merci pour ton retour et pour cette mise à jour.

Bl4ckfi3lds
